Update revit-adcof.md
alexandregrignon/MC-GT07-IFCINT pull request #5
Opened 2017-03-13 14:45 UTC by Ibex35

J'ai changé revit par archicad

2017-03-13 14:46 UTC, DUHEM-Progiscad approved these changes

2017-03-13 15:04 UTC, alexandregrignon requested changes

2017-03-13 15:04 UTC, alexandregrignon commented on _fiches/revit-adcof.md
>  source_nom: Revit
Modifier les en-têtes "source" également

2017-03-13 15:06 UTC, alexandregrignon approved these changes

2017-03-13 15:07 UTC, alexandregrignon commented
Je vous ai donné les droits d'administration si vous souhaitez valider la modification (bouton "Merge pull request")

2017-03-13 15:13 UTC, Ibex35 commented
ok
donc là si on fait "merge pull request" j'imagine que cela publie la modification sur le site? c'est cela?
en l'occurence c'est une fausse manipulation (on a changé revit par archicad), une fois publié on pourra revenir à avant la modification?

2017-03-13 15:16 UTC, merged

2017-03-13 15:16 UTC, Ibex35 commented
j'ai fait "merge pull request" pour voir

2017-03-13 15:19 UTC, alexandregrignon commented
Il est tout à fait possible d'annuler la modification ensuite : https://github.com/blog/1857-introducing-the-revert-button

2017-03-13 15:26 UTC, Ibex35 commented
ok, je n'ai pas vu ce bouton 'Revert' (pas disponible ou je ne l'ai pas vu)
mais de toute façon j'ai publié avec "merge pull request", puis je suis retourné dans "Améliorer cette page", j'ai remis ce qui était bien puis j'ai fait "commit directly to the master branch", au lieu de "create a new branch". J'imagine que j'ai le droit de le faire depuis que tu nous as mis en droits d'administrateur.

2017-03-13 18:06 UTC, DUHEM-Progiscad commented
Je ne dois visiblement pas suivre la même démarche ou avoir les mêmes
droits car je ne vois rien de tous ces boutons et/ou validations.

Le 13 mars 2017 à 16:26, Ibex35 <notifications@github.com> a écrit :

> ok, je n'ai pas vu ce bouton 'Revert' (pas disponible ou je ne l'ai pas vu)
> mais de toute façon j'ai publié avec "merge pull request", puis je suis
> retourné dans "Améliorer cette page", j'ai remis ce qui était bien puis
> j'ai fait "commit directly to the master branch", au lieu de "create a new
> branch". J'imagine que j'ai le droit de le faire depuis que tu nous as mis
> en droits d'administrateur.
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub
> <https://github.com/alexandregrignon/MC-GT07-IFCINT/pull/5#issuecomment-286141524>,
> or mute the thread
> <https://github.com/notifications/unsubscribe-auth/AZFI19OGx4zbGmUoypkoshxwsl5ld9_fks5rlWAQgaJpZM4MbWQ_>
> .
>

2017-03-14 06:56 UTC, Ibex35 commented
didier

je te donne mes identifiants pour que tu vois par toi meme, au cas ou
alexandre ne t'a pas créé les bons droits

https://github.com/login
yves.menez@cype.com
cily11052013


*Meilleures salutations,*
*Yves M**ÉNEZ*

*yves.menez@cype.com* <yves.menez@cype.com>


*CYPE* - *Software *pour l'*Architecture *et l'*Ingénierie* de la *Construction
- *
*www.cype.fr <http://www.cype.fr>*

Rendez-vous à *BEPOSITIVE, Stand 5F104!*

Demandez votre invitation avec le code* EMEXP:*

*[image: bepositive-logo-fr-highres]
<http://bepositive2017.site.exhibis.net/visiteur.htm>*

Rendez-vous à *BIM WORLD, Stand 243!*

Demandez votre invitation avec le code *EXZ6587:*



[image: signature] <https://bim-w.com/inscription/>
CYPE FRANCE

Tél. 02.30.96.17.44 -  Fax 02.22.44.25.08
2 rue du Chêne Morand - 35510 CESSON SEVIGNE


Le 13 mars 2017 à 19:06, DUHEM-Progiscad <notifications@github.com> a écrit
:

> Je ne dois visiblement pas suivre la même démarche ou avoir les mêmes
> droits car je ne vois rien de tous ces boutons et/ou validations.
>
> Le 13 mars 2017 à 16:26, Ibex35 <notifications@github.com> a écrit :
>
> > ok, je n'ai pas vu ce bouton 'Revert' (pas disponible ou je ne l'ai pas
> vu)
> > mais de toute façon j'ai publié avec "merge pull request", puis je suis
> > retourné dans "Améliorer cette page", j'ai remis ce qui était bien puis
> > j'ai fait "commit directly to the master branch", au lieu de "create a
> new
> > branch". J'imagine que j'ai le droit de le faire depuis que tu nous as
> mis
> > en droits d'administrateur.
> >
> > —
> > You are receiving this because you were mentioned.
> > Reply to this email directly, view it on GitHub
> > <https://github.com/alexandregrignon/MC-GT07-IFCINT/pull/5#issuecomment-
> 286141524>,
> > or mute the thread
> > <https://github.com/notifications/unsubscribe-auth/
> AZFI19OGx4zbGmUoypkoshxwsl5ld9_fks5rlWAQgaJpZM4MbWQ_>
> > .
>
> >
>
> —
> You are receiving this because you modified the open/close state.
> Reply to this email directly, view it on GitHub
> <https://github.com/alexandregrignon/MC-GT07-IFCINT/pull/5#issuecomment-286193286>,
> or mute the thread
> <https://github.com/notifications/unsubscribe-auth/AY2Z4vlBk3bkbrLr-LEmoB7Dcrbhzs2Cks5rlYWygaJpZM4MbWQ_>
> .
>

2017-03-14 07:04 UTC, Ibex35 commented
didier, (alexandre en copie)

ensuite tu vas sur
https://github.com/alexandregrignon/MC-GT07-IFCINT/edit/master/_fiches/
revit-adcof.md

tu fais un changement

tu choisis "create a new branch": c'est pour proposer une collaboration,
sans l'imposer en tant qu'administrateur (sinon tu ferais "commit directly
to the master branch")

ensuite tu fais un commentaire et "create pull request"

et ensuite tu fais "merge pull request" pour publier puis tu confirmes
'confirm merge request" je crois

dès lors tu pourras voir (ouvre le dans un autre onglet) ta modification
ici:
http://mc-gt07-ifcint.bimstandards.fr/fiches/revit-adcof/

reviens dans l'onglet précédent, tu verras que tu peux faire 'revert' pour
annuler la publication

et tu regardes de nouveau dans
http://mc-gt07-ifcint.bimstandards.fr/fiches/revit-adcof/




*Meilleures salutations,*
*Yves M**ÉNEZ*

*yves.menez@cype.com* <yves.menez@cype.com>


*CYPE* - *Software *pour l'*Architecture *et l'*Ingénierie* de la *Construction
- *
*www.cype.fr <http://www.cype.fr>*

Rendez-vous à *BEPOSITIVE, Stand 5F104!*

Demandez votre invitation avec le code* EMEXP:*

*[image: bepositive-logo-fr-highres]
<http://bepositive2017.site.exhibis.net/visiteur.htm>*

Rendez-vous à *BIM WORLD, Stand 243!*

Demandez votre invitation avec le code *EXZ6587:*



[image: signature] <https://bim-w.com/inscription/>
CYPE FRANCE

Tél. 02.30.96.17.44 -  Fax 02.22.44.25.08
2 rue du Chêne Morand - 35510 CESSON SEVIGNE


Le 14 mars 2017 à 07:56, Yves MENEZ <yves.menez@cype.com> a écrit :

> didier
>
> je te donne mes identifiants pour que tu vois par toi meme, au cas ou
> alexandre ne t'a pas créé les bons droits
>
> https://github.com/login
> yves.menez@cype.com
> cily11052013
>
>
> *Meilleures salutations,*
> *Yves M**ÉNEZ*
>
> *yves.menez@cype.com* <yves.menez@cype.com>
>
>
> *CYPE* - *Software *pour l'*Architecture *et l'*Ingénierie* de la *Construction
> - *
> *www.cype.fr <http://www.cype.fr>*
>
> Rendez-vous à *BEPOSITIVE, Stand 5F104!*
>
> Demandez votre invitation avec le code* EMEXP:*
>
> *[image: bepositive-logo-fr-highres]
> <http://bepositive2017.site.exhibis.net/visiteur.htm>*
>
> Rendez-vous à *BIM WORLD, Stand 243!*
>
> Demandez votre invitation avec le code *EXZ6587:*
>
>
>
> [image: signature] <https://bim-w.com/inscription/>
> CYPE FRANCE
>
> Tél. 02.30.96.17.44 -  Fax 02.22.44.25.08
> 2 rue du Chêne Morand - 35510 CESSON SEVIGNE
>
>
> Le 13 mars 2017 à 19:06, DUHEM-Progiscad <notifications@github.com> a
> écrit :
>
>> Je ne dois visiblement pas suivre la même démarche ou avoir les mêmes
>> droits car je ne vois rien de tous ces boutons et/ou validations.
>>
>> Le 13 mars 2017 à 16:26, Ibex35 <notifications@github.com> a écrit :
>>
>> > ok, je n'ai pas vu ce bouton 'Revert' (pas disponible ou je ne l'ai pas
>> vu)
>> > mais de toute façon j'ai publié avec "merge pull request", puis je suis
>> > retourné dans "Améliorer cette page", j'ai remis ce qui était bien puis
>> > j'ai fait "commit directly to the master branch", au lieu de "create a
>> new
>> > branch". J'imagine que j'ai le droit de le faire depuis que tu nous as
>> mis
>> > en droits d'administrateur.
>> >
>> > —
>> > You are receiving this because you were mentioned.
>> > Reply to this email directly, view it on GitHub
>> > <https://github.com/alexandregrignon/MC-GT07-IFCINT/pull/5#
>> issuecomment-286141524>,
>> > or mute the thread
>> > <https://github.com/notifications/unsubscribe-auth/AZFI19OGx
>> 4zbGmUoypkoshxwsl5ld9_fks5rlWAQgaJpZM4MbWQ_>
>> > .
>>
>> >
>>
>> —
>> You are receiving this because you modified the open/close state.
>> Reply to this email directly, view it on GitHub
>> <https://github.com/alexandregrignon/MC-GT07-IFCINT/pull/5#issuecomment-286193286>,
>> or mute the thread
>> <https://github.com/notifications/unsubscribe-auth/AY2Z4vlBk3bkbrLr-LEmoB7Dcrbhzs2Cks5rlYWygaJpZM4MbWQ_>
>> .
>>
>
>

2017-03-14 08:13 UTC, alexandregrignon commented
Attention, quand on répond aux mails de notifications, les réponses s'affichent ici (https://github.com/alexandregrignon/MC-GT07-IFCINT/pull/5#issuecomment-286338938).

Yves,
je me suis donc permis d'éditer tes commentaires pour que ton mot de passe n'apparaisse pas en clair sur le site.

Didier,
Voici le lien vers l'invitation à obtenir les droits d'administration : https://github.com/alexandregrignon/MC-GT07-IFCINT/invitations

2017-03-14 10:10 UTC, Ibex35 commented
merci alexandre

ah on est vraiment des innocents t'as vu? et on se veut éditeurs de
logiciels... c'est toujours les cordonniers les plus mal chaussés!


*Meilleures salutations,*
*Yves M**ÉNEZ*

*yves.menez@cype.com* <yves.menez@cype.com>


*CYPE* - *Software *pour l'*Architecture *et l'*Ingénierie* de la *Construction
- *
*www.cype.fr <http://www.cype.fr>*

Rendez-vous à *BEPOSITIVE, Stand 5F104!*

Demandez votre invitation avec le code* EMEXP:*

*[image: bepositive-logo-fr-highres]
<http://bepositive2017.site.exhibis.net/visiteur.htm>*

Rendez-vous à *BIM WORLD, Stand 243!*

Demandez votre invitation avec le code *EXZ6587:*



[image: signature] <https://bim-w.com/inscription/>
CYPE FRANCE

Tél. 02.30.96.17.44 -  Fax 02.22.44.25.08
2 rue du Chêne Morand - 35510 CESSON SEVIGNE


Le 14 mars 2017 à 09:13, Alexandre Grignon <notifications@github.com> a
écrit :

> Attention, quand on répond aux mails de notifications, les réponses
> s'affichent ici (#5 (comment)
> <https://github.com/alexandregrignon/MC-GT07-IFCINT/pull/5#issuecomment-286338938>
> ).
>
> Yves,
> je me suis donc permis d'éditer tes commentaires pour que ton mot de passe
> n'apparaisse pas en clair sur le site.
>
> Didier,
> Voici le lien vers l'invitation à obtenir les droits d'administration :
> https://github.com/alexandregrignon/MC-GT07-IFCINT/invitations
>
> —
> You are receiving this because you modified the open/close state.
> Reply to this email directly, view it on GitHub
> <https://github.com/alexandregrignon/MC-GT07-IFCINT/pull/5#issuecomment-286350371>,
> or mute the thread
> <https://github.com/notifications/unsubscribe-auth/AY2Z4knVZcXjOyv_SnvHOmCilbIN7Xbxks5rlkwrgaJpZM4MbWQ_>
> .
>